version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: chat-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    networks:
      - chat-network

  backend_replica:
    build:
      context: .
    container_name: chat-backend-replica
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    networks:
      - chat-network

  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"
    networks:
      - chat-network

  nginx:
    image: nginx:alpine
    container_name: chat-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - backend_replica
    networks:
      - chat-network

networks:
  chat-network:
